// Package imports
import Head from 'next/head';

// Component imports
import Navbar from '../components/Navbar';

// Style imports
import styles from '../styles/Home.module.scss';

// Data imports
import { navItems } from '../data/index';
import Header from '../components/Header';

export default function Home() {
	return (
		<div className={styles.home_wrapper}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<nav className={styles.nav_wrapper}>
				<div className={styles.container}>
					<Navbar logo={navItems.logo} links={navItems.links} />
				</div>
			</nav>

			<main className={styles.main}>
				<header className={styles.header}>
					<Header />
				</header>
			</main>
		</div>
	);
}
