// Package imports
import Head from 'next/head';

// Component imports
import Navbar from '../components/Navbar';
import Header from '../components/Header';

// Style imports
import styles from '../styles/Home.module.scss';

// Data imports
import { navData, headerData, buttonData } from '../data/index';

export default function Home() {
	return (
		<div className={styles.home_wrapper}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<nav className={styles.nav_wrapper}>
				<div className={styles.container}>
					<Navbar logo={navData.logo} links={navData.links} />
				</div>
			</nav>

			<main className={styles.main}>
				<header className={styles.header}>
					<div className={styles.container}>
						<Header
							title={headerData.title}
							body={headerData.body}
							images={headerData.images}
						/>
					</div>
				</header>
			</main>
		</div>
	);
}
